name: aamusted_timetable_generator
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  window_manager: ^0.3.9
  flutter_acrylic: ^1.1.4
  flutter_smart_dialog: ^4.9.7+8
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  open_app_file: ^4.0.2
  syncfusion_flutter_xlsio: ^26.1.42
  http: ^1.2.2
  url_launcher: ^6.3.0
  string_similarity: ^2.0.0
  syncfusion_flutter_pdf: ^26.1.42
  fluent_ui: ^4.9.0
  go_router: ^14.2.1
  pdf: ^3.11.0
  google_fonts: ^6.2.1
  file_picker: ^8.0.6
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  excel: ^4.0.3
  path_provider: ^2.1.3
  # data_table_2: ^2.5.12
  collection: ^1.18.0
  # screenshot: ^2.3.0
  badges: ^3.1.2
  mongo_dart: ^0.10.3
  flutter_markdown: ^0.7.3
  media_kit: ^1.1.10+1                             # Primary package.
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4 
  cloud_firestore: ^5.1.0
  firebase_core: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: any
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  fonts:
    - family: FluentIcons
      fonts:
        - asset: assets/FluentIcons.ttf

#flutter pub run flutter_native_splash:create
#flutter packages pub run build_runner build --delete-conflicting-outputs

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/logo_light.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false
    image_path: "assets/logo_light.png"